# Gems
gems: [jekyll-paginate, jekyll-gist]
paginate: 5
paginate_path: "page:num"

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            hexfact0r
tagline:          'CTF team'
description:      'Writeups'
url:              http://hexfact0r.dk
baseurl:          /

author:
  name:           'hexfact0r'
  url:            https://twitter.com/hexfact0r

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/hexfact0r/hexfact0r.github.io 
